<?php
$reguiones = array("Cibao Norte","Cibao Sur","Cibao Nordeste","Cibao Noroeste","Valdesia","El Valle","Enriquillo","Yuma","Higuamo","Ozama");

function genCategories($arr){
    $res = "";
    foreach($arr as $a){
        $res.="'{$a}',";
    }
    $res = substr($res,0,-1);
    return $res;
}
function genDataSeries($arr){
    $res = "";
    foreach($arr as $a){
        $res.="['{$a}',".rand(500, 8000)."],";
    }
    $res = substr($res,0,-1);
    return $res;
}
?>
<script  src="<?php echo DEFAULT_ASSETS?>javascripts/highcharts.js"></script>
<script  src="<?php echo DEFAULT_ASSETS?>modules/exporting.js"></script>
<script async type="text/javascript">
    $(function () {
        $('#container').highcharts({
            chart: {
                type: 'bar'
            },
            title: {
                text: 'Frecuencia del uso del Internet'
            },
            subtitle: {
                text: ''
            },
            xAxis: {
                categories: ["Todos los días",
                    "Varios días a la semana",
                    "Una vez a la semana",
                    "Algunas veces al mes",
                    "Cada 3 meses",
                    "Sin información"]

            },
            yAxis: {
                min: 0,
                title: {
                    text: 'Porcentaje'
                }
            },
            tooltip: {
                headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                    '<td style="padding:0"><b>{point.y:.1f} %</b></td></tr>',
                footerFormat: '</table>',
                shared: true,
                useHTML: true
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },
            series: [{
                name: "Cibao Norte",
                data: [15.5,26.8,21.3,30.6,3.7,2.1]
            }, {
                name: "Cibao Sur",
                data: [8.8,30.5,24.8,30.1,3.2,2.6]
            }, {
                name: "Cibao Nordeste",
                data: [10.8,31.5,21.2,32.1,2.8,1.6]
            }, {
                name: "Cibao Nordoeste",
                data: [7.2,37.2,13.0,27.5,10.3,4.8]
            }, {
                name: "Valdesia",
                data: [12.7,21.2,20.7,40.5,3.6,1.3]
            }, {
                name: "El Valle",
                data: [15.3,33.4,22.9,25.1,2.1,1.2]
            }, {
                name: "Enriquillo",
                data: [9.3,25.0,31.7,30.2,3.7,0.0]
            }, {
                name: "Yuma",
                data: [10.2,37.0,27.7,20.9,3.2,1.0]
            }, {
                name: "Higuamo",
                data: [11.4,48.4,19.8,15.0,2.1,3.4]
            }, {
                name: "Ozama",
                data: [21.7,31.8,16.3,24.9,2.8,2.4]
            }
            ]
        });
    });


</script>


<div id="container" style="min-width: 200px; height: 1400px; margin: 0 auto"></div>