<?php
$provincias = array("DISTRITO NACIONAL","AZUA","BAORUCO","BARAHONA","DUARTE","EL SEIBO","ESPAILLAT","INDEPENDENCIA","LA ALTAGRACIA","LA ROMANA","LA VEGA","MONTE CRISTI","PEDERNALES","PERAVIA","PUERTO PLATA","HERMANAS MIRABAL","SAN JUAN","SANTIAGO","VALVERDE","MONTE PLATA","HATO MAYOR","SANTO DOMINGO");

function genCategories($arr){
    $res = "";
    foreach($arr as $a){
        $res.="'{$a}',";
    }
    $res = substr($res,0,-1);
    return $res;
}
function genDataSeries($arr){
    $res = "";
    foreach($arr as $a){
        if($a == "SANTO DOMINGO" || $a == "DISTRITO NACIONAL"){
            $res.="['{$a}',".rand(8000, 15000)."],";
        }
        else{
            $res.="['{$a}',".rand(500, 8000)."],";
        }

    }
    $res = substr($res,0,-1);
    return $res;
}
?>
<script  src="<?php echo DEFAULT_ASSETS?>javascripts/highcharts.js"></script>
<script  src="<?php echo DEFAULT_ASSETS?>modules/exporting.js"></script>
<div id="indicador4"></div>
<script async type="text/javascript">
    $('#indicador4').highcharts({
        chart: {
            type: 'bar'
        },
        title: {
            text: 'Promedio de calificacion de estudiantes divididos por provincia y sexo'
        },
        subtitle: {
            text: 'Promedio de calificacion de estudiantes divididos por provincia y sexo (Demostración)'
        },
        xAxis: {
            categories: [<?php echo genCategories($provincias); ?>],
            title: {
                text: null
            }
        },
        yAxis: {
            min: 0,
            max:100,
            title: {
                text: '',
                align: 'high'
            },
            labels: {
                overflow: 'justify'
            }
        },
        tooltip: {
            valueSuffix: ''
        },
        plotOptions: {
            bar: {
                dataLabels: {
                    enabled: true
                }
            }
        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'top',
            x: -100,
            y: 100,
            floating: true,
            borderWidth: 1,
            backgroundColor: '#FFFFFF',
            shadow: true
        },
        credits: {
            enabled: false
        },
        series: [{
            name: 'Masculino',
            data: [88, 91, 88, 92, 87, 95, 80, 82, 87, 93, 96, 94, 82, 91, 82, 91, 88, 85, 89, 94, 93, 90]
        }, {
            name: 'Femenino',
            data: [96, 94, 82, 91, 82, 91, 88, 85, 89, 94, 93, 90,88, 91, 88, 92, 87, 87, 80, 82, 87, 93]
        }]
    });

</script>