<?php
$reguiones = array("Cibao Norte","Cibao Sur","Cibao Nordeste","Cibao Noroeste","Valdesia","El Valle","Enriquillo","Yuma","Higuamo","Ozama");

function genCategories($arr){
    $res = "";
    foreach($arr as $a){
        $res.="'{$a}',";
    }
    $res = substr($res,0,-1);
    return $res;
}
function genDataSeries($arr){
    $res = "";
    foreach($arr as $a){
        $res.="['{$a}',".rand(500, 8000)."],";
    }
    $res = substr($res,0,-1);
    return $res;
}
?>
<script  src="<?php echo DEFAULT_ASSETS?>javascripts/highcharts.js"></script>
<script  src="<?php echo DEFAULT_ASSETS?>modules/exporting.js"></script>
<script async type="text/javascript">
    $(function () {
        $('#container').highcharts({
            chart: {
                type: 'bar'
            },
            title: {
                text: '¿En qué lugar ha usado Internet en los últimos 12 meses?'
            },
            subtitle: {
                text: ''
            },
            xAxis: {
                categories: ["¿Ha usado el Internet últimos 12 meses fuera o dentro del hogar?",
                    "En la casa",
                    "En el trabajo",
                    "El lugar de estudio",
                    "Casa de otra persona",
                    "Lugar público gratuito",
                    "Centro de llamada",
                    "Área de uso inalámbrico",
                    "Otros"]

            },
            yAxis: {
                min: 0,
                title: {
                    text: 'Porcentaje'
                }
            },
            tooltip: {
                headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                    '<td style="padding:0"><b>{point.y:.1f} %</b></td></tr>',
                footerFormat: '</table>',
                shared: true,
                useHTML: true
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },
            series: [{
                name: "Cibao Norte",
                data: [25.6,18.0,18.5,40.0,37.6,10.0,71.1,2.9,0.2]
            }, {
                name: "Cibao Sur",
                data: [18.9,16.4,17.3,40.0,37.4,5.5,63.4,1.1,0.0]
            }, {
                name: "Cibao Nordeste",
                data: [13.4,18.8,19.3,19.6,18.7,.6,43.0,.0,0.6]
            }, {
                name: "Cibao Nordoeste",
                data: [20.2,6.0,25.1,52.5,34.2,22.7,57.5,11.0,1.7]
            }, {
                name: "Valdesia",
                data: [16.5,13.8,21.3,28.5,24.8,9.3,68.1,.4,0.8]
            }, {
                name: "El Valle",
                data: [13.6,10.4,17.0,30.2,12.1,16.0,59.5,.6,0.0]
            }, {
                name: "Enriquillo",
                data: [10.9,7.3,14.5,18.6,19.2,8.3,57.1,1.6,0.0]
            }, {
                name: "Yuma",
                data: [23.3,11.9,16.5,24.9,23.3,9.5,60.6,4.6,0.0]
            }, {
                name: "Higuamo",
                data: [18.1,10.2,21.8,19.5,15.8,7.5,64.6,1.3,0.0]
            }, {
                name: "Ozama",
                data: [37.4,29.3,31.2,23.4,28.4,5.8,60.9,2.0,0.8]
            }
            ]
        });
    });


</script>


<div id="container" style="min-width: 200px; height: 1400px; margin: 0 auto"></div>

</body>
</html>
